DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  username VARCHAR(55) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(55) NOT NULL UNIQUE,
  name VARCHAR(55) NOT NULL,
  surname VARCHAR(55) NOT NULL,
  is_admin BOOL,
  is_active BOOL DEFAULT TRUE,
  email_token INT,
  verified   BOOL DEFAULT FALSE, 
  courses    TEXT DEFAULT '',  
  pc         VARCHAR(255) DEFAULT '',  
  os VARCHAR(20) DEFAULT '',  
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS apps;
CREATE TABLE apps (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name VARCHAR(55) NOT NULL,
  process_name VARCHAR(55) NOT NULL,
  os VARCHAR(55) NOT NULL,
  is_active BOOL DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS courses;
CREATE TABLE courses (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  title VARCHAR(44) NOT NULL,
  description VARCHAR(480) NOT NULL,
  author VARCHAR(25) NOT NULL,
  thumbnail VARCHAR(155) NOT NULL,
  preview VARCHAR(155) NOT NULL,
  rating INTEGER DEFAULT 0, 
  num_reviews INTEGER DEFAULT 0, 
  duration VARCHAR(25) NOT NULL, 
  is_active BOOL DEFAULT FALSE,
  sort_order INTEGER, 
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
