DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  username VARCHAR(55) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(55) NOT NULL UNIQUE,
  name VARCHAR(55) NOT NULL,
  surname VARCHAR(55) NOT NULL,
  is_admin BOOL,
  is_active BOOL DEFAULT TRUE,
  email_token INT,
  verified   BOOL DEFAULT FALSE, 
  courses    TEXT DEFAULT '',  
  pc         VARCHAR(255) DEFAULT '',  
  os VARCHAR(20) DEFAULT '',  
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS apps;
CREATE TABLE apps (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name VARCHAR(55) NOT NULL,
  process_name VARCHAR(55) NOT NULL,
  os VARCHAR(55) NOT NULL,
  is_active BOOL DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS courses;
CREATE TABLE courses (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  title VARCHAR(44) NOT NULL,
  description VARCHAR(480) NOT NULL,
  author VARCHAR(25) NOT NULL,
  thumbnail VARCHAR(155) NOT NULL,
  preview VARCHAR(155) NOT NULL,
  rating INTEGER, 
  num_reviews INTEGER, 
  duration VARCHAR(25) NOT NULL, 
  is_active BOOL DEFAULT FALSE,
  sort_order INTEGER, 
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS videos;
CREATE TABLE videos (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  title VARCHAR(15) NOT NULL,
  description VARCHAR(55) NOT NULL,
  video_hls VARCHAR(255) NOT NULL,
  thumbnail VARCHAR(155) NOT NULL,
  length VARCHAR(155) NOT NULL, 
  views INTEGER, 
  course_id INTEGER NOT NULL, 
  sort_order INTEGER, 
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS files;
CREATE TABLE files (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  path VARCHAR(255) NOT NULL,
  video_id INTEGER NOT NULL, 
  sort_order INTEGER, 
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS history;
CREATE TABLE history (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  video_id INTEGER NOT NULL,
  course_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  video_resume VARCHAR(55) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS reivews;
CREATE TABLE reviews (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  course_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  description VARCHAR(255) NOT NULL,
  rating INTEGER, 
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
